import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from '@/lib/utils';
import MainHeader from "@/components/MainHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Food Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-slate-300")}>
        <MainHeader></MainHeader>
        {children}
      </body>
    </html>
  );
}
